apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-springboot
  labels:
    app: sample-springboot
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-springboot
  template:
    metadata:
      labels:
        app: sample-springboot
    spec:
      containers:
      - image: 191845259489.dkr.ecr.ap-northeast-2.amazonaws.com/your-repo-name:68
        imagePullPolicy: Always
        name: sample-flask
        ports:
        - containerPort: 8080
          protocol: TCP
